quarkus:
  devservices:
    enabled: false
  live-reload:
    enabled: true
  langchain4j:
    pgvector:
      dimension: 256
  datasource:
    username: ricardo-reis
    password: isThisNotAVerySecurePassword
    jdbc:
      url: jdbc:postgresql://localhost:15432/pessoa_faladora
  transaction-manager:
    default-transaction-timeout: 1000s
  hibernate-orm:
    physical-naming-strategy: me.davidgomesdev.db.RepositoryNaming
